version: 2.1

orbs:
  tools: replikativ/clj-tools@0

jobs:
  build:
    executor: tools/clojurecli
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: clean
          command: clojure -T:build clean
      - run:
          name: jar
          command: clojure -T:build jar
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .m2
            - .npm
            - replikativ

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          context: dockerhub-deploy
      - tools/format:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/unittest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/integrationtest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - build:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/deploy:
          context:
            - dockerhub-deploy
            - clojars-deploy
          filters:
            branches:
              only: main
          requires:
            - tools/format
            - tools/unittest
            - tools/integrationtest
            - build
      - tools/release:
          context:
            - dockerhub-deploy
            - github-token
          filters:
            branches:
              only: main
          requires:
            - tools/deploy
