version: 2.1

orbs:
  tools: replikativ/clj-tools@0

workflows:
  build-test-and-deploy:
    jobs:
      - tools/setup:
          context: dockerhub-deploy
      - tools/format:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/unittest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/integrationtest:
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/build:
          jarname: "hitchhiker-tree"
          context: dockerhub-deploy
          requires:
            - tools/setup
      - tools/deploy:
          context:
            - dockerhub-deploy
          filters:
            branches:
              only: main
          requires:
            - tools/format
            - tools/unittest
            - tools/integrationtest
            - tools/build
      - tools/release:
          context:
            - dockerhub-deploy
            - github-token
          filters:
            branches:
              only: main
          requires:
            - tools/deploy
